CREATE TABLE CBPARK68.MVC_BOARD(
UNQ NUMBER PRIMARY KEY,
TITLE VARCHAR2(100) NOT NULL,
PASS VARCHAR2(100) NOT NULL,
NAME VARCHAR2(20),
CONTENT VARCHAR2(4000),
HITS NUMBER,
RDATE TIMESTAMP)
TABLESPACE ORA_DATA01;